services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: marcador-sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@sswordSeguro123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "P@sswordSeguro123", "-C", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 3s
      retries: 10

  api:
    build:
      context: ./Marcador.Api
      dockerfile: Dockerfile
    container_name: marcador-api
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=MarcadorDb;User Id=sa;Password=P@sswordSeguro123;TrustServerCertificate=True;
    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy

volumes:
  mssql_data:
